import os
from flask import Flask, render_template, request, redirect, url_for
from werkzeug.utils import secure_filename
from google.cloud import aiplatform
from google.protobuf import json_format
from google.protobuf.struct_pb2 import Value

# Configuration
UPLOAD_FOLDER = 'static/uploads'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

# TODO: User needs to set these values
PROJECT_ID = "your-gcp-project-id"  # <--- REPLACE WITH YOUR PROJECT ID
LOCATION = "us-central1"        # <--- REPLACE WITH YOUR GCP REGION (e.g., us-central1)
MODEL_ID = "imagetext@0.0.1"    # Image captioning model

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/upload', methods=['POST'])
def upload_image():
    if 'image' not in request.files:
        return render_template('index.html', error="No image selected")

    file = request.files['image']
    if file.filename == '':
        return render_template('index.html', error="No image selected")

    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
        file.save(filepath)

        try:
            # Ensure PROJECT_ID and LOCATION are not the placeholder values
            if PROJECT_ID == "your-gcp-project-id" or LOCATION == "us-central1":
                print("PROJECT_ID or LOCATION not configured in app.py. Using placeholders.")
                # This error message is more for the developer/user running the app
                error_message = "The application is not configured with your Google Cloud Project ID and Location. Please update app.py."
                # For the user of the web app, show a generic message
                user_facing_error = "Image processing service is not configured. Please contact the administrator."
                # Log the detailed error for the server console
                print(f"Configuration error: {error_message}")
                return render_template('index.html', error=user_facing_error, uploaded_image=filename)

            description = get_image_description(filepath)
            return render_template('index.html', description=description, uploaded_image=filename)
        except Exception as e:
            # Log the full error for debugging on the server
            print(f"Error calling Vertex AI API: {e}")
            # Provide a generic error to the user
            return render_template('index.html', error=f"Error processing image. Ensure your GCP project and region are correctly configured, the Vertex AI API is enabled, and you have authenticated correctly.", uploaded_image=filename)
    else:
        return render_template('index.html', error="Invalid file type. Allowed types: png, jpg, jpeg, gif")

def get_image_description(image_path: str) -> str:
    '''
    Uses Vertex AI Imagen model to generate a description for an image.
    '''
    aiplatform.init(project=PROJECT_ID, location=LOCATION)

    client_options = {"api_endpoint": f"{LOCATION}-aiplatform.googleapis.com"}
    client = aiplatform.gapic.PredictionServiceClient(client_options=client_options)

    import base64
    with open(image_path, "rb") as f:
        image_bytes = base64.b64encode(f.read()).decode("utf-8")

    instance = json_format.ParseDict(
        {"bytesBase64Encoded": image_bytes}, Value()
    )
    instances = [instance]

    parameters = json_format.ParseDict({"number_of_results": 1, "language": "en"}, Value())

    endpoint = (
        f"projects/{PROJECT_ID}/locations/{LOCATION}/"
        f"publishers/google/models/{MODEL_ID}"
    )

    response = client.predict(
        endpoint=endpoint, instances=instances, parameters=parameters
    )

    if response.predictions and len(response.predictions) > 0 and len(response.predictions[0]) > 0:
        # Assuming the first prediction and first caption is what we want.
        # The structure of response.predictions can be a list of lists or list of dicts
        # depending on the model. For imagetext@0.0.1, it's typically a list of captions.
        # predictions: [[“a cat sitting on a couch”]]
        prediction_result = response.predictions[0]
        if isinstance(prediction_result, (list, tuple)) and len(prediction_result) > 0:
            return prediction_result[0]
        elif isinstance(prediction_result, str): # If it's already a string
            return prediction_result
        else:
            # Fallback if the structure is unexpected
            print(f"Unexpected prediction structure: {prediction_result}")
            return "Could not parse description from API response."

    return "No description generated by the API."


if __name__ == '__main__':
    if not os.path.exists(UPLOAD_FOLDER):
        os.makedirs(UPLOAD_FOLDER)
    app.run(debug=True)
